site:
  title: TEB tuts
  url: http://canopee.org/docs/teb192021
  start_page: resTEB::index.adoc

content:
  sources:
   - url: .
     branches: master
     #tags: [1.0.*, 1.1.*]
     #start_path: documentation
  #Tutorial repositories
  # - url: https://github.com/couchbaselabs/tutorials.git
    # branches: master
    # start-path: docs
  # - url: https://github.com/couchbaselabs/tutorial-template.git
    # branches: master
  # - url: https://github.com/couchbaselabs/mobile-travel-sample.git
    # branches: master
    # start-path: content
  # - url: https://github.com/couchbaselabs/hotel-finder-react-native.git
    # branches: master

asciidoc:
  attributes:
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: ''
    hide-uri-scheme: ''
    lang: 'fr'
    icons: 'font'
    data-uri: 'yes'
    stem: 'mathjax'
    eqnums: 'yes'
    linkattrs: ''
  extensions:
  - ./lib/json-config-ui-block-macro.js
  - ./lib/inline-man-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/tabs-block.js
  - ./lib/tabs.js

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
  
output:
  clean: true
  dir: ./build
